### PR TITLE
query params passed to markdown library

### PR DESCRIPTION
**Pull request by darul75**
hi,

I needed specific options to pass to markdown library 

https://github.com/chjj/marked

So here is a PR to enhance loader with webpack query params feature:

http://webpack.github.io/docs/loaders.html

It uses https://github.com/webpack/loader-utils and assign library but I think it is a good match ;)

https://github.com/sindresorhus/object-assign

### CODE REVIEW

**Comment by dimotsai** [comment]
@darul75  Good job! :+1:

**Comment by darul75** [comment]
thx :+1:

**Comment by darul75** [comment]
is this PR acceptable and will merged, thanks

**Comment by jhnns** [comment]
@darul75 this one looks good, thank you! :+1:

Please don't bump the `package.json` version next time, this should be done by the guy who publishes the package imho.

**Comment by darul75** [comment]
ok, thx

**Pull request merged**
